// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsykJcr3KM3CfuHdEK0FjvLxhKHhUy4kk',
    appId: '1:758001550845:web:27aff25f9935588bdf4594',
    messagingSenderId: '758001550845',
    projectId: 'hybrid-order-system',
    authDomain: 'hybrid-order-system.firebaseapp.com',
    storageBucket: 'hybrid-order-system.firebasestorage.app',
    measurementId: 'G-9YDP33Z9EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIqYhgQQAAJhnhM3VWoCvLk2Oi-gHauDQ',
    appId: '1:758001550845:android:2d4d4b91d7ab356cdf4594',
    messagingSenderId: '758001550845',
    projectId: 'hybrid-order-system',
    storageBucket: 'hybrid-order-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXofyTFckJjzCFfXru1ijJHQQo7H_zS-w',
    appId: '1:758001550845:ios:771cd49d4324b792df4594',
    messagingSenderId: '758001550845',
    projectId: 'hybrid-order-system',
    storageBucket: 'hybrid-order-system.firebasestorage.app',
    iosClientId: '758001550845-vq8rtf2e0jej9ajk4jmmjr4q3jlpogku.apps.googleusercontent.com',
    iosBundleId: 'com.keita.mobileOrderApp',
  );
}
